CI: Fix Bugs with `lasy` 0.6.1 (#5836)
`lasy` 0.6.1 is available after
https://github.com/LASY-org/lasy/pull/393 and it is now downloaded
automatically when we install dependencies for our CI tests.

This PR fixes a bug in our test scripts, occurring with the new version:
```bash
TypeError: LaguerreGaussianTransverseProfile.__init__() missing 1 required positional argument: 'wavelength'
```